routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('people','PeopleController');
Route::get('people/destroy/{id}', ['as' => 'people/destroy', 'uses' => 'PeopleController@destroy']);
Route::post('people/show', ['as' => 'people/show', 'uses' => 'PeopleController@show']);

Route::resource('competence','competenceController');
Route::get('competence/destroy/{id}', ['as' => 'competence/destroy', 'uses' => 'competenceController@destroy']);
Route::post('competence/show', ['as' => 'competence/show', 'uses' => 'competenceController@show']);

Route::resource('learningResult','learningResultController');
Route::get('learningResult/destroy/{id}', ['as' => 'learningResult/destroy', 'uses' => 'learningResultController@destroy']);
Route::post('learningResult/show', ['as' => 'learningResult/show', 'uses' => 'learningResultController@show']);

Route::resource('groupNumber','GroupNumberController');
Route::get('groupNumber/destroy/{id}', ['as' => 'groupNumber/destroy', 'uses' => 'GroupNumberController@destroy']);
Route::post('groupNumber/show', ['as' => 'groupNumber/show', 'uses' => 'GroupNumberController@show']);

Route::resource('program','ProgramController');
Route::get('program/destroy/{id}', ['as' => 'program/destroy', 'uses' => 'ProgramController@destroy']);
Route::post('program/show', ['as' => 'program/show', 'uses' => 'ProgramController@show']);

Route::resource('rol','RoleController');
Route::get('rol/destroy/{id}', ['as' => 'rol/destroy', 'uses' => 'RoleController@destroy']);
Route::post('rol/show', ['as' => 'rol/show', 'uses' => 'RoleController@show']);

Route::resource('state','StateController');
Route::get('state/destroy/{id}', ['as' => 'state/destroy', 'uses' => 'StateController@destroy']);
Route::post('state/show', ['as' => 'state/show', 'uses' => 'StateController@show']);


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Learning_Result.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Learning_Result extends Model
{
    protected $table='learning_results';
	protected $fillable = ['learningresults_description','competence_id'];
    protected $guarded = ['id'];

    public function competence() {
    	return $this->belongsTo('App\Models\Competence');
    } 
}

app/Http/Controllers/LearningResultController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Models\Learning_Result as Learning_Result;
use App\Models\Competence as Competence;

class LearningResultController extends Controller
{
	public function destroy($id)
    {
        $learningResult = learning_Result::find($id);
        $learningResult->delete();
        return redirect()->back();
    }
    public function edit($id)
    {
        $learningResult = learning_Result::find($id);
        $competence = Competence::all();        
        return \View::make('learningResults/update',compact('learningResult','competence'));
    }
    public function update($id, Request $request)
    {
        $learningResult = learning_Result::find($id);
        $learningResult->learningResult_description = $request->description;
        $learningResult->competence_id = $request->competence;        
        $learningResult->save();
        return redirect('learningResult');
    }
    public function index()
    {
        $learningResult = learning_Result::all();
        $competence = Competence::all();
        return \View::make('learningResults/list',compact('learningResult','competence'));
    }
    public function create()
    {
        $competence = Competence::all();
    	return \View::make('learningResults/new', compact('learningResult','competence'));
    }
    public function store(Request $request)
    {           
    	$learningResult = new Learning_Result;
    	$learningResult->learningResult_description = $request->description;
    	$learningResult->competence_id= $request->competence;    	
        $learningResult->save();
        return redirect('learningResult');
    }
}

resources/views/learningResults/list.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-12">
				{!!Form::open(['route' => 'learningResult/show','method' => 'post','novalidate', 'class' => 'form-inline'])!!}
				<div class="form-group">
					<label>Descripción</label>
					<input type="text" name="description" class="form-control">	
				</div>
				<div class="form-group">
					<!-- <button type="submit" class="btn btn-default">Buscar</button> -->
					<a href="{{route('learningResult.index')}}" class="btn btn-primary">Ver Todo</a>
					<a href="{{route('learningResult.create')}}" class="btn btn-primary">Crear</a>
				</div>
				{!! Form::close() !!}
			</article>
			<article class="col-md-12">
				<table class="table table-info table-condensed table-striped table-bordered ">
					<thead>
						<tr>
							<th>Descripción</th>
							<th>Competencia</th>							
						</tr>
					</thead>
					<tbody>
						@foreach($learningResult as $learningResult1)
							<tr>								
								<td>{{ $learningResult1->learningresult_description}}</td>
								<td>{{ $learningResult1->competence->competence_description}}</td>								
								<td>
									<a href="{{ route('learningResult.edit',['id' => $learningResult1->id]) }}" class="btn btn-info">Editar</a>
									<a href="{{ route('learningResult/destroy',['id' => $learningResult1->id]) }}" class="btn btn-danger">Eliminar</a>
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</article>
		</div>
	</section>
@endsection

resources/views/learningResults/new.blade.php
@extends('layouts.app')
@section('content')
    <section class="container">
        <div class="row">
            <article class="col-md-10 col-md-offset-1">
				{!!Form::open(['route' => 'learningResult.store','method' => 'post','novalidate'])!!}
                <div class="form-group row">
                    <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Descripcion del resultado de aprendizaje') }}</label>

                    <div class="col-md-6">
                        <input id="description" type="text" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" value="{{ old('description') }}" required autofocus>

                        @if ($errors->has('description'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('description') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
				<div class="form-group row">
                    <label for="program" class="col-md-4 col-form-label text-md-right">{{ __('Seleccione la competencia') }}</label>
                    <div class="col-md-6">
                        <select id="competence" class="form-control" name="competence" required autofocus>
                            @foreach($competence as $competence1)
                                <option value="{{$competence1->id}}">{{$competence1->competence_description}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
				
    			<div class="form-group row mb-0">
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            {{ __('Registrar') }}
                        </button>
                    </div>
                </div>
                {!! Form::close() !!}
            </article>
		</div>
	</section>
@endsection

resources/views/learningResults/update.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!! Form::model($learningResult,['route' => ['learningResult.update',$learningResult->id],'method' => 'put','novalidate']) !!}
				<div class="form-group row">
                    <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Descripcion del resultado de aprendizaje') }}</label>
                    <div class="col-md-6">
                        <input id="description" type="text" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" value="{{ $learningResult->learningresult_description}}" required autofocus>

                        @if ($errors->has('description'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('description') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
				<div class="form-group row">
                    <label for="competence" class="col-md-4 col-form-label text-md-right">{{ __('Seleccione la Competencia') }}</label>
                    <div class="col-md-6">
                         <select id="competence" class="form-control" name="competence" required autofocus>
                            @foreach($competence as $competence1)
                                <option value="{{$competence1->id}}">{{$competence1->competence_description}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>				
    			<div class="form-group row mb-0">
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            {{ __('Actualizar') }}
                        </button>
                    </div>
                </div>
                {!! Form::close() !!}
			</article>
		</div>
	</section>
@endsection