routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('people','PeopleController');
Route::get('people/destroy/{id}', ['as' => 'people/destroy', 'uses' => 'PeopleController@destroy']);
Route::post('people/show', ['as' => 'people/show', 'uses' => 'PeopleController@show']);

Route::resource('competence','competenceController');
Route::get('competence/destroy/{id}', ['as' => 'competence/destroy', 'uses' => 'competenceController@destroy']);
Route::post('competence/show', ['as' => 'competence/show', 'uses' => 'competenceController@show']);

Route::resource('learningResult','learningResultController');
Route::get('learningResult/destroy/{id}', ['as' => 'learningResult/destroy', 'uses' => 'learningResultController@destroy']);
Route::post('learningResult/show', ['as' => 'learningResult/show', 'uses' => 'learningResultController@show']);

Route::resource('groupNumber','GroupNumberController');
Route::get('groupNumber/destroy/{id}', ['as' => 'groupNumber/destroy', 'uses' => 'GroupNumberController@destroy']);
Route::post('groupNumber/show', ['as' => 'groupNumber/show', 'uses' => 'GroupNumberController@show']);

Route::resource('program','ProgramController');
Route::get('program/destroy/{id}', ['as' => 'program/destroy', 'uses' => 'ProgramController@destroy']);
Route::post('program/show', ['as' => 'program/show', 'uses' => 'ProgramController@show']);

Route::resource('rol','RoleController');
Route::get('rol/destroy/{id}', ['as' => 'rol/destroy', 'uses' => 'RoleController@destroy']);
Route::post('rol/show', ['as' => 'rol/show', 'uses' => 'RoleController@show']);

Route::resource('state','StateController');
Route::get('state/destroy/{id}', ['as' => 'state/destroy', 'uses' => 'StateController@destroy']);
Route::post('state/show', ['as' => 'state/show', 'uses' => 'StateController@show']);


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/State.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class State extends Model
{
	protected $table='states';
	protected $fillable = ['state'];
    protected $guarded = ['id'];
}

app/Http/Controllers/StateController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\State as State;

class StateController extends Controller
{
	public function destroy($id)
    {
        $state = State::find($id);
        $state->delete();
        return redirect()->back();
    }
    public function edit($id)
    {
    	$state = State::find($id);        
        return \View::make('state/update',compact('state'));
    }
    public function update($id, Request $request)
    {
        $state = State::find($id);
        $state->state = $request->name;
        $state->save();
        return redirect('state');
    }
    public function index()
    {
        $state = State::all();        
        return \View::make('state/list', compact('state'));
    }
    public function create()
    {        
    	return \View::make('state/new', compact('state'));
    }
    public function store(Request $request)
    {           
    	$state = new State;
    	$state->state = $request->name;
        $state->save();
        return redirect('state');
    }
}

resources/views/state/list.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-12">
				{!!Form::open(['route' => 'state/show','method' => 'post','novalidate', 'class' => 'form-inline'])!!}
				<div class="form-group">
					<label>Nombre</label>
					<input type="text" name="name" class="form-control">	
				</div>
				<div class="form-group">
					<!-- <button type="submit" class="btn btn-default">Buscar</button> -->
					<a href="{{route('state.index')}}" class="btn btn-primary">Ver Todo</a>
					<a href="{{route('state.create')}}" class="btn btn-success">Crear</a>
				</div>
				{!! Form::close() !!}
			</article>
			<article class="col-md-12">
				<table class="table table-info table-condensed table-striped table-bordered ">
					<thead>
						<tr>
							<th>Nombre</th>
							<th>Acción</th>
						</tr>
					</thead>
					<tbody>
						@foreach($state as $state1)
							<tr>
								<td>{{ $state1->state}}</td>								
								<td>
									<a href="{{ route('state.edit',['id' => $state1->id]) }}" class="btn btn-info">Editar</a>
									<a href="{{ route('state/destroy',['id' => $state1->id]) }}" class="btn btn-danger">Eliminar</a>
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</article>
		</div>
	</section>
@endsection

resources/views/state/new.blade.php
@extends('layouts.app')
@section('content')
    <section class="container">
        <div class="row">
            <article class="col-md-10 col-md-offset-1">
				{!!Form::open(['route' => 'state.store','method' => 'post','novalidate'])!!}
                <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Nombre Del Estado') }}</label>
                    <div class="col-md-6">
                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required autofocus>

                        @if ($errors->has('name'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>				
    			<div class="form-group row mb-0">
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-success">
                            {{ __('Registrar') }}
                        </button>
                    </div>
                </div>
                {!! Form::close() !!}
            </article>
		</div>
	</section>
@endsection

resources/views/state/update.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!! Form::model($state,['route' => ['state.update',$state->id],'method' => 'put','novalidate']) !!}
				<div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Nombre Del Estado') }}</label>
                    <div class="col-md-6">
                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ $state->state}}" required autofocus>
                        @if ($errors->has('name'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
    			<div class="form-group row mb-0">
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            {{ __('Actualizar') }}
                        </button>
                    </div>
                </div>
                {!! Form::close() !!}
			</article>
		</div>
	</section>
@endsection