routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('people','PeopleController');
Route::get('people/destroy/{id}', ['as' => 'people/destroy', 'uses' => 'PeopleController@destroy']);
Route::post('people/show', ['as' => 'people/show', 'uses' => 'PeopleController@show']);

Route::resource('competence','competenceController');
Route::get('competence/destroy/{id}', ['as' => 'competence/destroy', 'uses' => 'competenceController@destroy']);
Route::post('competence/show', ['as' => 'competence/show', 'uses' => 'competenceController@show']);

Route::resource('learningResult','learningResultController');
Route::get('learningResult/destroy/{id}', ['as' => 'learningResult/destroy', 'uses' => 'learningResultController@destroy']);
Route::post('learningResult/show', ['as' => 'learningResult/show', 'uses' => 'learningResultController@show']);

Route::resource('groupNumber','GroupNumberController');
Route::get('groupNumber/destroy/{id}', ['as' => 'groupNumber/destroy', 'uses' => 'GroupNumberController@destroy']);
Route::post('groupNumber/show', ['as' => 'groupNumber/show', 'uses' => 'GroupNumberController@show']);

Route::resource('program','ProgramController');
Route::get('program/destroy/{id}', ['as' => 'program/destroy', 'uses' => 'ProgramController@destroy']);
Route::post('program/show', ['as' => 'program/show', 'uses' => 'ProgramController@show']);

Route::resource('rol','RoleController');
Route::get('rol/destroy/{id}', ['as' => 'rol/destroy', 'uses' => 'RoleController@destroy']);
Route::post('rol/show', ['as' => 'rol/show', 'uses' => 'RoleController@show']);

Route::resource('state','StateController');
Route::get('state/destroy/{id}', ['as' => 'state/destroy', 'uses' => 'StateController@destroy']);
Route::post('state/show', ['as' => 'state/show', 'uses' => 'StateController@show']);


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Competence.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Competence extends Model
{
    protected $table='competences';
	protected $fillable = ['competence_description','program_id','state_id'];
    protected $guarded = ['id'];

    public function program() {
    	return $this->belongsTo('App\Models\Program');
    } 

    public function state() {
    	return $this->belongsTo('App\Models\State');
    } 
}

app/Http/Controllers/CompetenceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Competence as Competence;
use App\Models\Program as Program;
use App\Models\State as State;

class CompetenceController extends Controller
{
	public function destroy($id)
    {
        $competence = Competence::find($id);
        $competence->delete();
        return redirect()->back();
    }
    public function edit($id)
    {
    	$state = State::all();
        $competence = Competence::find($id);
        $program = Program::all();
        return \View::make('competence/update',compact('competence','program','state'));
    }
    public function update($id, Request $request)
    {
        $competence = Competence::find($id);
        $competence->competence_description = $request->description;
        $competence->program_id= $request->program;
        $competence->state_id= $request->state;
        $competence->save();
        return redirect('competence');
    }
    public function index()
    {
        $competence = Competence::all();
        $program = Program::all();
        return \View::make('competence/list',compact('competence','program'));
    }
    public function create()
    {
        $program = Program::all();
    	return \View::make('competence/new', compact('competence','program'));
    }
    public function store(Request $request)
    {   
        //Instanciacion de clase Competence e invocacion de atributos para registro de Competencia
    	$competence = new Competence;
    	$competence->competence_description = $request->description;
    	$competence->program_id= $request->program;
    	$competence->state_id = 1;
        $competence->save();
        return redirect('competence');
    }
}

resources/views/competence/list.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-12">
				{!!Form::open(['route' => 'competence/show','method' => 'post','novalidate', 'class' => 'form-inline'])!!}
				<div class="form-group">
					<label>Nombre</label>
					<input type="text" name="name" class="form-control">	
				</div>
				<div class="form-group">
					<!-- <button type="submit" class="btn btn-default">Buscar</button> -->
					<a href="{{route('competence.index')}}" class="btn btn-primary">Ver Todo</a>
					<a href="{{route('competence.create')}}" class="btn btn-primary">Crear</a>
				</div>
				{!! Form::close() !!}
			</article>
			<article class="col-md-12">
				<table class="table table-info table-condensed table-striped table-bordered ">
					<thead>
						<tr>
							<th>Descripcion</th>
							<th>Programa</th>
							<th>Estado</th>
						</tr>
					</thead>
					<tbody>
						@foreach($competence as $competence1)
							<tr>
								<td>{{ $competence1->competence_description}}</td>
								<td>{{ $competence1->program->program_name}}</td>
								<td>{{ $competence1->state->state}}</td>
								<td>
									<a href="{{ route('competence.edit',['id' => $competence1->id]) }}" class="btn btn-info">Editar</a>
									<a href="{{ route('competence/destroy',['id' => $competence1->id]) }}" class="btn btn-danger">Eliminar</a>
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</article>
		</div>
	</section>
@endsection

resources/views/competence/new.blade.php
@extends('layouts.app')
@section('content')
    <section class="container">
        <div class="row">
            <article class="col-md-10 col-md-offset-1">
				{!!Form::open(['route' => 'competence.store','method' => 'post','novalidate'])!!}
                <div class="form-group row">
                    <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Descripcion de la competencia') }}</label>

                    <div class="col-md-6">
                        <input id="description" type="text" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" value="{{ old('description') }}" required autofocus>

                        @if ($errors->has('description'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('description') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

				<div class="form-group row">
                    <label for="program" class="col-md-4 col-form-label text-md-right">{{ __('Seleccione el Programa') }}</label>

                    <div class="col-md-6">
                        <select id="program" class="form-control" name="program" required autofocus>
                            @foreach($program as $program1)
                                <option value="{{$program1->id}}">{{$program1->program_name}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
				
    			<div class="form-group row mb-0">
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            {{ __('Register') }}
                        </button>
                    </div>
                </div>
                {!! Form::close() !!}
            </article>
		</div>
	</section>
@endsection

resources/views/competence/update.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!! Form::model($competence,['route' => ['competence.update',$competence->id],'method' => 'put','novalidate']) !!}
				<div class="form-group row">
                    <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Descripcion de la competencia') }}</label>

                    <div class="col-md-6">
                        <input id="description" type="text" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" value="{{ $competence->competence_description}}" required autofocus>

                        @if ($errors->has('description'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('description') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

				<div class="form-group row">
                    <label for="program" class="col-md-4 col-form-label text-md-right">{{ __('Seleccione el Programa') }}</label>

                    <div class="col-md-6">
                        <select id="program" class="form-control" name="program" required autofocus>
                            @foreach($program as $program1)
                                <option value="{{$program1->id}}">{{$program1->program_name}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
				

				<div class="form-group row">
                    <label for="state" class="col-md-4 col-form-label text-md-right">{{ __('Seleccione el Estado') }}</label>

                    <div class="col-md-6">
                        <select id="state" class="form-control" name="state" required autofocus>
                            @foreach($state as $state1)
                                <option value="{{$state1->id}}">{{$state1->state}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
				
    			<div class="form-group row mb-0">
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            {{ __('Register') }}
                        </button>
                    </div>
                </div>
                {!! Form::close() !!}
			</article>
		</div>
	</section>
@endsection