routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('people','PeopleController');
Route::get('people/destroy/{id}', ['as' => 'people/destroy', 'uses' => 'PeopleController@destroy']);
Route::post('people/show', ['as' => 'people/show', 'uses' => 'PeopleController@show']);

Route::resource('competence','competenceController');
Route::get('competence/destroy/{id}', ['as' => 'competence/destroy', 'uses' => 'competenceController@destroy']);
Route::post('competence/show', ['as' => 'competence/show', 'uses' => 'competenceController@show']);

Route::resource('learningResult','learningResultController');
Route::get('learningResult/destroy/{id}', ['as' => 'learningResult/destroy', 'uses' => 'learningResultController@destroy']);
Route::post('learningResult/show', ['as' => 'learningResult/show', 'uses' => 'learningResultController@show']);

Route::resource('groupNumber','GroupNumberController');
Route::get('groupNumber/destroy/{id}', ['as' => 'groupNumber/destroy', 'uses' => 'GroupNumberController@destroy']);
Route::post('groupNumber/show', ['as' => 'groupNumber/show', 'uses' => 'GroupNumberController@show']);

Route::resource('program','ProgramController');
Route::get('program/destroy/{id}', ['as' => 'program/destroy', 'uses' => 'ProgramController@destroy']);
Route::post('program/show', ['as' => 'program/show', 'uses' => 'ProgramController@show']);

Route::resource('rol','RoleController');
Route::get('rol/destroy/{id}', ['as' => 'rol/destroy', 'uses' => 'RoleController@destroy']);
Route::post('rol/show', ['as' => 'rol/show', 'uses' => 'RoleController@show']);

Route::resource('state','StateController');
Route::get('state/destroy/{id}', ['as' => 'state/destroy', 'uses' => 'StateController@destroy']);
Route::post('state/show', ['as' => 'state/show', 'uses' => 'StateController@show']);


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Asistencia</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
        <!-- {{ config('app.name', 'Asistencia') }} -->
    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link rel="icon" href="{{ asset('images/Sena.ico') }}">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav id="navbarIni"class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container-fluid">
                  <a class="navbar-brand" href="http://www.sena.edu.co" >
                    <img src="{{ asset('images/Sena_logo.png') }}" width="35" height="35" alt="">
                  </a>
                <a class="navbar-brand" href="{{ url('/') }}">
                    Gestion de Asistencias
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <!-- <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li> -->
                            <!-- <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li> -->
                        @else
                            <li class="nav-item">
                                <a class="nav-link " href="{{ url('/home') }}" role="button">Inicio</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspoup="true" aria-expanded="false">Gestion de Personas</a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{route('people.create')}}">Registro</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{{route('people.index')}}">Consulta</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspoup="true" aria-expanded="false">Gestion de Competencias</a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{route('competence.create')}}">Registro</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{{route('competence.index')}}">Consulta</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspoup="true" aria-expanded="false">Gestion de RAP</a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{route('learningResult.create')}}">Registrar</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{{route('learningResult.index')}}">Consultar</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspoup="true" aria-expanded="false">Gestion de Fichas</a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{route('groupNumber.create')}}">Registrar</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{{route('groupNumber.index')}}">Consultar</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspoup="true" aria-expanded="false">Gestion de Programas</a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{route('program.create')}}">Registrar</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{{route('program.index')}}">Consultar</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspoup="true" aria-expanded="false">Gestion de Roles</a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{route('rol.create')}}">Registrar</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{{route('rol.index')}}">Consultar</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspoup="true" aria-expanded="false">Gestion de Estados</a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{route('state.create')}}">Registrar</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{{route('state.index')}}">Consultar</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>